lib/src/dio.dart
test/dio_test.dart

Fix cancel download request didnot reutrn a CANCEL type DioError. And add test case for cancellation of download request.looking forward your review!  @wendux @Sky24n @asmh1989 @calebisstupid @cdvv7788
Before I fix it, the test case for cancellation of download request sometimes failed with below message. And it is not always fail because the time to connect varies.
```
DioError [DioErrorType.DEFAULT]: HttpException: Connection closed while receiving data, uri = http://download.dcloud.net.cn/HBuilder.9.0.2.macosx_64.dmg
dart:async                       _Completer.completeError
package:dio/src/dio.dart 257:19  Dio.download.<fn>
===== asynchronous gap ===========================
dart:_http                       _HttpClientResponse.listen
package:dio/src/dio.dart 236:12  Dio.download
===== …
```

Fix: cancel download request didnot reutrn a CANCEL type DioError

---

lib/src/dio.dart

I want to authenticate http clients by overwriting onError interceptor, authenticating and rerunning the request. But when returning the new successful request the returned request would get transformed and lose statusCode and other information.

when wrapping response object, make sure to keep status code, etc. intact

---

README-ZH.md
README.md
lib/src/cancel_token.dart
lib/src/dio.dart

The "onError" interceptor should only trigger once for a bad request.  E.g.
`() async {
try {
Dio dio = Dio(BaseOptions(baseUrl: 'http://www.example.com'));
dio.interceptors.add(InterceptorsWrapper(
onError: (DioError e) {
print("Intercepted error");
return e;
}
));
await dio.get('/badRequest');
} catch (e) {
print("Caught error");
}
}();`

Don't call the "onError" interceptor twice. E.g. for HTTP 404

---

package_src/lib/src/options.dart

Allows `queryParameters` to be merged on `BaseOptions`

Fix `queryParameters` merge on `BaseOptions`

---

README-ZH.md
README.md

Hey, thanks for such a great http client library.
I was so impressed by this work and I'm know fan of this.
As I follow the introduction in README, I found that `BaseOptions` usage example was not correctly assigning to the right type. (By the way IDE told me this was error)
Therefore I updated the README for the newbies.
If I was misunderstanding something just let me know.
Thanks

Fix example in README using BaseOptions

---

package_src/lib/src/dio_error.dart

`dart.core.Error` is intended to be used for program failures and shouldn't be caught. `DioError extends Error` which is odd because errors like timeouts are intended to be caught. Therefore `DioError` should implement `Exception`.
From the `dart.core.Error` documentation:
```
* Error objects thrown in the case of a program failure.
*
* An `Error` object represents a program failure that the programmer
* should have avoided.
*
* Examples include calling a function with invalid arguments,
* or even with the wrong number of arguments,
* or calling it at a time when it is not allowed.
*
* These are not errors that a caller should expect or catch -
* if they occur, the program is erroneous,
* and terminating the program may be the safest response.
*
* Since errors are not created to be …
```

Make DioError catchable by implementing Exception instead of Error

---

package_src/lib/src/dio.dart
package_src/test/exception_test.dart

Fixes #309 
Fixes the regression introduced in #304 not throwing exceptions correctly.
I know that it is already fixed by @wendux in `2.1.5` by changing `DioError` to `DioError extends Error implements Exception`. This PR allows the removal of `extends Error` which would be dart idiomatic as explained in #304.
Sadly I can't PR the change on top of `2.1.5` because the changes haven't been pushed.
I added tests that DioErros are thrown and catchable.

Throw exceptions

---

package_src/lib/src/dio.dart

Added check for system errors when writing a file to disk. Under some circumstances, FileSystemException errors occur. For example
FileSystemException: writeFrom failed, path = '/storage/emulated/0/Download/151.pdf' (OS Error: No space left on device, errno = 28)

Fix catch exception

---

dio/lib/src/form_data.dart

1. 修复3.0.4及3.0.6因为header格式颠倒导致的无法上传到OSS，如#534
2. 修复3.0.5中因为header中的filename字段有问题，导致后台无法识别上传文件, 如#562

fix upload image header error, support both oss and other server

---

dio/lib/src/entry/dio_for_native.dart

This pull request fixes a problem on the native environment, where the file being downloaded cannot be saved if the path doesn't exist yet.
This error can be seem mostly on desktop environments, like Windows.
I think this closes those issues:
https://github.com/flutterchina/dio/issues/643
https://github.com/flutterchina/dio/issues/609

Fixing download method failing when the directory doesn't exist yet.

---

plugins/http2_adapter/lib/src/http2_adapter.dart
plugins/http2_adapter/test/http2_test.dart

This merge request fixes / refers to the following issues: 
The current HTTP2 adapter doesn't work when the request contains a payload, because it only starts sending the payload after the response header from the server has been received. However, the server won't start sending the response header until the entire payload is received from the client. Hence the connection is in a deadlock until either the client or the server times out.
This pull request fixes this issue by transmitting the entire payload body before starting to listen for responses.
...

Fixes the HTTP2 Adapter for Requests with Payload

---

dio/lib/src/dio.dart

HTTP servers MUST NOT include any content when sending a 304. When treating
304 as success, the response body is empty and transforming the response
leads to an empty string. This then fails in `assureResponse` when
`response.data` is assigned to the variable of type `T` (which is usually
not String, but the expected body type like `List<dynamic>`) with an
exception: type 'String' is not a subtype of type 'List<dynamic>'
By treating 304 as a failure, the request throws a DioError that can
easily be checked for the statusCode and then the application can handle
the 304 however it wants to (usually by reusing the data from the cache).
I did not add a test or updated the documentation, since I wanted to get feedback on this first. I know that I could supply a custom `validateStatus` callback …

do not treat 304 as good status code by default

---

plugins/cookie_manager/README.md

if you use `1.0.x`
you are getting an exception running flutter 
```
rror on line 46, column 23 of pubspec.yaml: Invalid version constraint: Could not parse version "1.0.x". Unknown text at "1.0.x".
╷
46 │   dio_cookie_manager: 1.0.x
│                       ^^^^^
╵
pub get failed (65;    ╵)
```
- [ x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [ x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
- [ x] I have added the required tests to prove the fix/feature I am adding
- [ x] I have updated the documentation (if necessary)
- [ x] I have run the tests and they pass
...

fixed version reference

---

dio/lib/src/headers.dart
dio/lib/src/options.dart
dio/lib/src/utils.dart

This merge request fixes / refers to the following issues:
TarekkMA/gql_dio_link#4
The current implementation of the headers do allow multiple header with different letter case.
for example the following header are considered as unique.
Content-type: xxxxxx
content-type: xxxxxx
CoNtEnT-TyPe: xxxxx
The current solution I have used is the same used in http package
https://github.com/dart-lang/http/blob/master/lib/src/base_request.dart#L89
...

make headers case insensitive

---

dio/lib/src/adapters/io_adapter.dart

This merge request fixes / refers to the following issues: #844 
When a user was connected to wifi while there was no internet connection available, Dio would not throw a CONNECT_TIMEOUT exception.
This commit fixes that issue.

#844 Throw CONNECT_TIMEOUT on wifi with no internet

---

dio/lib/src/dio.dart
dio/pubspec.yaml
dio/test/interceptor_test.dart

When interceptor.onResponse return normal object, next interceptor's onResponse will be skip. the PR fix this.

Prevent skip response interceptor when onResponse return normal object.

---

dio/lib/dio.dart

Migration to null safety accidentally hid the DioMixin class from the public facing API. This change would re-expose it to the public facing API.
The null-safety pull request hid DioMixin from the public facing API. This pull request exports 'src/dio_mixin.dart' to the public facing API.

Export DioMixin

---

dio/lib/src/adapters/browser_adapter.dart

If the reduce method is called on an empty stream (like Stream.empty()), a Bad State: No Element exception is thrown. This change adds a check to determine if the stream is empty before sending the request. If the stream is empty, the request is sent but if the stream is not empty, the stream is reduced before being sent.
I ran into this issue when using doing a get request on flutter web.
When using dio on web, like in dio's flutter example, a get request will fail and return a Bad State: No Element exception. This is caused by the reduce method being called on an empty stream. This pull requests adds a check to determine if the stream is empty before reducing it to prevent a Bad State: No element error.

Prevents Bad State: No Element from being thrown

---

README.md

This merge request fixes / refers to the following issues: README out of date for onResponse function example
- Changed the example onResponse function return under "Simple interceptor example" to match the latest code.
- onResponse does not return a Future any more, it is now a void function.

Update the Simple interceptor example in README.md

---

dio/CHANGELOG.md
dio/lib/src/adapter.dart
dio/lib/src/adapters/browser_adapter.dart

This makes `ResponseBody.statusCode` non-nullable. It improves the API a little bit.
It's safe to change this as [`http`](https://github.com/dart-lang/http/blob/1e42ffa181b263f7790f276a5465832bff7ce615/lib/src/browser_client.dart#L57) also does this and has even wider adoption rates.

Make `ResponseBody.statusCode` non-nullable

---

dio/CHANGELOG.md
dio/README.md
dio/lib/src/adapter.dart
dio/lib/src/adapters/universal_adapter.dart
dio/test/echo_adapter.dart
dio/test/mock_adapter.dart
example/lib/adapter.dart
plugins/http2_adapter/lib/src/http2_adapter.dart

This PR makes it possible to instantiate a `HttpClientAdapter` which is platform independent.
Partly fixes #1362
This is a breaking change if people decided to extend `HttpClientAdapter`.

Make it possible to instantiate a universal adapter

---

dio/CHANGELOG.md
dio/lib/src/entry/dio_for_native.dart

This merge request fixes / refers to the following issues: N/A
Before we delete the downloading file, we should determine whether it exists.

fix: Only delete file when it exists

---

dio/CHANGELOG.md
dio/lib/src/adapter.dart
dio/lib/src/adapters/browser_adapter.dart

It was a breaking change, so we have to revert it.
cc @kuhnroyal

Revert "It's safe for status code to be non-null"

---

.github/workflows/dio.yml
dio/CHANGELOG.md
dio/lib/src/adapters/browser_adapter.dart
dio/test/basic_test.dart
dio/test/readtimeout_test.dart
dio/test/upload_stream_test.dart

could check case https://github.com/morlay/roundtripper/runs/4862938300?check_suite_focus=true
When using `BrowserHttpClientAdapter` cancel hangs until timeout. `DefaultHttpClientAdapter` work well.
```
00:39 +4: test/basic_test.dart: cancel                                                                                                                                                                 
00:40 +4: test/basic_test.dart: cancel                                                                                                                                                                 
00:41 +4: test/basic_test.dart: cancel …
```

Fix BrowserHttpClientAdapter canceled hangs

---

dio/test/exception_test.dart

Additional tests to ensure `badCertificateCallback`. It can also serve as an example.
I hope it's in the right place.

add badssl to exception_test.dart

---

dio/lib/src/adapters/io_adapter.dart

- https://github.com/flutterchina/dio/issues/1229
- https://github.com/flutterchina/dio/pull/1387
`browser_adapter` abort request when timeout occurs.
https://github.com/flutterchina/dio/blob/6d04ec95d951bdecd19a2939d94de217d2d1ff7d/dio/lib/src/adapters/browser_adapter.dart#L78
https://github.com/flutterchina/dio/blob/6d04ec95d951bdecd19a2939d94de217d2d1ff7d/dio/lib/src/adapters/browser_adapter.dart#L102
https://github.com/flutterchina/dio/blob/6d04ec95d951bdecd19a2939d94de217d2d1ff7d/dio/lib/src/adapters/browser_adapter.dart#L128
`io_adapter` detach socket when `receiveTimeout` is occurs.
https://github.com/flutterchina/dio/blob/6d04ec95d951bdecd19a2939d94de217d2d1ff7d/dio/lib/src/adapters/io_adapter.dart#L119
But …

fix: abort request when timeout occurs

---

dio/CHANGELOG.md
dio/README-ZH.md
dio/README.md
dio/lib/src/dio_mixin.dart
dio/lib/src/interceptor.dart
dio/lib/src/interceptors/imply_content_type.dart
dio/lib/src/options.dart
dio/migration_guide.md
dio/test/interceptor_test.dart
dio/test/options_test.dart

Reverts the functionality of cfug/diox#69.
Resolves #1667 #1661 #1653 #1650 #1648 #1646
- The interceptor can be removed by calling `Interceptor.removeImplyContentTypeInterceptor`.
- The interceptor was intended not to be exposed to outside usages.

✨ `ImplyContentTypeInterceptor`

---

dio/CHANGELOG.md
dio/lib/src/interceptors/imply_content_type.dart

For the web platform, an inline `bool.fromEnvironment` translates to `core.bool.fromEnvironment` instead of correctly being replaced by the constant value found in the environment at build time.
See https://github.com/flutter/flutter/issues/51186.
This fix is unfortunately not something we can test for as far as I can tell. I've tried numerous methods of automating the detection of the issue (and thus the fix), but it seems to only appear when running the Flutter example in a browser.

Fix "unsupported operation" error on web platform

---

dio/CHANGELOG.md
dio/lib/src/options.dart
dio/lib/src/transformer.dart
dio/lib/src/transformers/sync_transformer.dart
dio/lib/src/utils.dart
dio/test/encoding_test.dart

Changes and test for correct encoding of collections in query parameters.
I am totally not sure if the encoding for `x-www-form-urlencoded` is supposed to be different from query parameters.

Fix encoding of query parameters

---

dio/README-ZH.md
dio/README.md
dio/lib/src/form_data.dart
dio/lib/src/multipart_file.dart

Help issues like #482 to understand what happened exactly.
As an improvement with comments and docs, it doesn't require a version change.

Improve exceptions and documents for `FormData` and `MultipartFile`

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/test/basic_test.dart
dio/test/interceptor_test.dart
dio/test/mock/adapters.dart

Fixes #1512.
Previously, `listenCancelForAsyncTask` will wait for `CancelToken.whenCancel` in certain scenarios:
https://github.com/cfug/dio/blob/6544701ed370e6ceaf81576f393459605e9a612f/dio/lib/src/dio_mixin.dart#L457-L466
These scenarios include `DioErrorType.cancel`, in which the error handler has been put into the event loop rather than executed immediately, which means the handler will handle the exception after the request is completed.

🐛 Fix `DioErrorType.cancel` in `Interceptors`

---

plugins/cookie_manager/CHANGELOG.md
plugins/cookie_manager/lib/src/cookie_mgr.dart
plugins/cookie_manager/test/cookies_test.dart

🐛 Fix empty cookie header parsing and header value set

---

.github/workflows/tests.yml
plugins/native_dio_adapter/CHANGELOG.md
plugins/native_dio_adapter/lib/native_dio_adapter.dart
plugins/native_dio_adapter/lib/src/cronet_adapter.dart
plugins/native_dio_adapter/lib/src/cupertino_adapter.dart
plugins/native_dio_adapter/lib/src/native_adapter.dart
plugins/native_dio_adapter/pubspec.yaml

updates cronet_http and cupertino_http dependencies and updates the code for their breaking changes

feat(native_dio_adapter): bump cronet_http, cupertino_http dependency

---

plugins/cookie_manager/CHANGELOG.md
plugins/cookie_manager/README.md
plugins/cookie_manager/lib/src/cookie_mgr.dart
plugins/cookie_manager/test/cookies_test.dart

Fix #1715.
When using `followRedirects` there's no way to handle the cookie value, and `Set-Cookie` won't be passed through the redirection. This also happened with the `http` library, the cookie is not available for redirections if `Set-Cookie` happen during redirects.

🐛 Allow to parse `Set-Cookie` with redirected response

---

dio/README-ZH.md
dio/README.md

📝 Fix interceptor codes in READMEs

---

dio/CHANGELOG.md
dio/README-ZH.md
dio/README.md
dio/lib/src/adapters/browser_adapter.dart
dio/lib/src/adapters/io_adapter.dart
dio/test/browser_test.dart
dio/test/exception_test.dart
dio/test/pinning_test.dart
example/lib/certificate_pinning.dart
example/lib/formdata.dart
example/lib/proxy.dart

Methods in `BrowserHttpClientAdapter` and `IOHttpClientAdapter` can be defined directly through their constructor instead of updates after the creation.

🚀 Allow defining adapter methods through their constructors

---

.github/workflows/tests.yml
plugins/http2_adapter/lib/src/connection_manager_imp.dart

In a recent release of `http2_adapter`, the publishing job failed because our CI didn't raise lint warnings about the `info` level. Adding `--fatal-infos` will let the analyze step raises warnings for all type of lint exceptions.

🚨 Analyze repos with fatal infos

---

dio/CHANGELOG.md
dio/lib/src/transformers/sync_transformer.dart
dio/lib/src/utils.dart
dio/test/encoding_test.dart
dio/test/url_encoded_test.dart

Fixes wrong default format used for comparison during encoding.
This should fix #1758

[dio] Fix wrong default encoding being used for lists

---

dio/README.md

⚠ This is my first pull request to OSS. Sorry if I made a mistake.
I just added async to CustomInterceptors.onError in dio/README.md.
async may not be necessary, but without it, "body_might_complete_normally" will occur.
Currently it is an error. I think the solution is either.
1. remove Future.
2. add "async".
If 1 is better, I will modify it.

Add async to CustomInterceptors.onError in dio/README.md.

---

dio/CHANGELOG.md
dio/README-ZH.md
dio/README.md
dio/lib/src/interceptors/log.dart

When running the app on systems focused on application analysis, such as [BrowserStack](https://www.browserstack.com) , same in profile mode , the request logs can leak unwanted information, even if the developer has the option to remove the print, most of them are not aware of these "leaks" of requests.
This opens the way for an attacker who has an apk , aab or any other file that the browserStack
accept, be able to run the app on the website and view the logs
So I suggest the inclusion of this little code that by default only executes the prints in debug mode

improve log interceptor

---

dio/CHANGELOG.md
dio/README-ZH.md
dio/README.md
dio/lib/src/adapters/io_adapter.dart
dio/lib/src/utils.dart
dio/test/adapters_test.dart
dio/test/exception_test.dart
dio/test/pinning_test.dart
dio/test/readtimeout_test.dart
example/lib/certificate_pinning.dart
example/lib/formdata.dart
example/lib/proxy.dart

The return type of `OnHttpClientCreate` has been changed from `HttpClient?` to `HttpClient`.
While technically a breaking change, it is considered a bug because the callback was actually
a no-op when the provided client was modified but not returned.
Fixes 1. of #1811

Fix return type of OnHttpClientCreate

---

dio/CHANGELOG.md
dio/lib/src/adapters/io_adapter.dart
dio/migration_guide.md
dio/test/adapters_test.dart

Remove deprecated `IOHttpClientAdapter.onHttpClientCreate`

Remove deprecated `IOHttpClientAdapter.onHttpClientCreate`

---

.github/workflows/tests.yml
dio/CHANGELOG.md
dio/pubspec.yaml
example/pubspec.yaml
plugins/cookie_manager/pubspec.yaml
plugins/http2_adapter/pubspec.yaml

I suggest we raise the min Dart version to 2.17.0 in 6.0.0
* support of `pubspec_overrides.yaml` in min Dart version tests
* support of `Error. throwWithStackTrace`
* required for mockitos `@GenerateNiceMocks`

Bump min Dart version to 2.17.0

---

dio/CHANGELOG.md
dio/lib/src/adapters/io_adapter.dart

* fixes #1801 - I think we should not provide a customisation option directly, all customisation can be done via `createHttpClient` instead. I also don't understand why we did default to 3 seconds.

Remove custom idleTimeout in IOHttpClientAdapter

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/test/upload_test.dart

A previous change to improve the performance of binary uploads accidentally broke the functionality of uploading `List<int>` json bodies.
Fixes #1858

Revert changes to List<int> body data handling

---

dio/test/stacktrace_test.dart
dio/test/upload_test.dart

* restore base64 comparison in upload tests - httpbun has base64 data now implemented
* add tests for async SocketException being thrown in IO adapter

Test improvements

---

dio/CHANGELOG.md
dio/lib/src/options.dart
dio/test/options_test.dart

This PR ensures consistent handling of "/" when concatenating the baseUrl with the path.
Previously, if the baseUrl had a trailing "/" or the path had a leading "/", the resulting URL would contain duplicate slashes.
To address this issue, the algorithm has been modified to insert only a single "/" regardless of whether the baseUrl has a trailing slash or the path has a leading slash. This improvement enhance the reliability and correctness of the concatenation process, providing a more robust solution.

[dio] Ensure consistent handling of "/" in concatenation of baseUrl with path

---

plugins/http2_adapter/CHANGELOG.md
plugins/http2_adapter/lib/src/connection_manager_imp.dart
plugins/http2_adapter/test/http2_test.dart

`_ConnectionManager._connect` may throw SocketException when call `await initFuture`,if it occurs, even if the network is restored, subsequent requests with the same domain will still obtain the cached initFuture, and it will still fail

fix(http2_adapter):request by http2 without network once,the same domain request will never success.

---

dio/test/pinning_test.dart
plugins/http2_adapter/test/pinning_test.dart
test.sh

`test.sh` is not necessary for the repo anymore.

🔥 Remove `test.sh`

---

analysis_options.yaml
dio/CHANGELOG.md
dio/README-ZH.md
dio/README.md
dio/lib/io.dart
dio/lib/src/adapter.dart
dio/lib/src/adapters/io_adapter.dart
dio/lib/src/interceptor.dart
dio/pubspec.yaml
dio/test/adapters_test.dart
plugins/cookie_manager/pubspec.yaml
plugins/http2_adapter/pubspec.yaml

Resolves blockers to the Flutter Favorite Program.

Fix pub scores

---

dio/pubspec.yaml
plugins/cookie_manager/README.md
plugins/cookie_manager/pubspec.yaml
plugins/http2_adapter/README.md
plugins/http2_adapter/pubspec.yaml
plugins/native_dio_adapter/pubspec.yaml

Topics are supported on pub.dev. The PR add topics for all packages.

Add topics to packages

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/test/dio_mixin_test.dart

See https://github.com/cfug/dio/pull/1772/files#r1281588318.
Fixes https://github.com/parse-community/Parse-SDK-Flutter/issues/958.

Revert removed `download` for `DioMixin`

---

dio/lib/src/transformers/sync_transformer.dart
dio/test/transformer_test.dart

- Optimize the `SyncTransformer.transformResponse` method and it‘s test.

Optimize SyncTransformer.transformResponse

---

dio/lib/src/dio.dart
dio/test/download_test.dart
dio/test/request_test.dart
dio/test/utils.dart
example/lib/dio.dart
example/lib/download.dart
example/lib/download_with_trunks.dart
example/lib/formdata.dart
example_flutter_app/lib/main.dart

- Improve tests.
- Improve usage example for `Dio.download`.
- Remove unused code.
- Fix typo in `example/lib/download_with_trunks`.
- Replace the broken resource: http://download.dcloud.net.cn/HBuilder.9.0.2.macosx_64.dmg.
- Disable the compression to assure the value of `total` argument of `onReceiveProgress` is not `-1` in `example/lib/download`.
There was no warning previously due to the default `dynamic` parameter type.

Improve usage example and tests

---

dio/CHANGELOG.md
dio/lib/src/options.dart

Removes the accidentally added `options` argument for `Options.compose` by 75cf9166c3d5d159895de123e24a9ce748804a1a.
Resolves #1934.

Remove `Options.compose(options)`

---

dio/test/formdata_test.dart
dio/test/mock/_formdata
dio/test/multipart_file_test.dart

Adjust test setting custom MultipartFile.contentType

---

.idea/modules.xml
example/.gitignore
example/melos_dio_example.iml
example_flutter_app/pubspec.yaml
example_flutter_app/test/widget_test.dart
melos.yaml
melos_dio_workspace.iml
plugins/native_dio_adapter/.gitignore

* mainly rename workspace project to avoid conflicts in IDEA (2x dio project)
* add examples to melos (not sure if this is what we want?)
* add .gitignore where missing

Improve melos configuration

---

dio/CHANGELOG.md
dio/lib/src/interceptor.dart
dio/test/interceptor_test.dart

Resolves #1973
The PR only addresses `clear`. However, lists can be modified in various ways which might also remove/replace the interceptor. We might need to rethink an extra internal interceptors list.

🐛 Avoid `Interceptors.clear` removes `ImplyContentTypeInterceptor`

---

.github/workflows/publishable.yml
dio/CHANGELOG.md

Inspired by https://github.com/dart-lang/pub-dev/issues/6012.

👷 Add `README.md` & `CHANGELOG.md` size check for publishable tests

---

dio/README-ZH.md
dio/README.md
dio/lib/src/interceptors/log.dart

Improve docs for LogInterceptor

---

plugins/cookie_manager/CHANGELOG.md
plugins/cookie_manager/lib/src/cookie_mgr.dart
plugins/cookie_manager/test/cookies_persistance_test.dart

Upon relative redirect, cookies were not saved because the `host` was missing. `resolveUri` provides the proper host info for a redirect Uri in such cases and doesn't affect others.

[cookie_manager] Fix `FileSystemException` when saving redirect cookies without a proper `host`

---

README-ZH.md
README.md
dio/README-ZH.md
dio/README.md
example/pubspec.yaml
plugins/cookie_manager/README.md
plugins/http2_adapter/README.md
plugins/native_dio_adapter/README.md

Walk through all READMEs and fix them.

📝 Fix READMEs

---

dio/CHANGELOG.md
dio/lib/src/dio_exception.dart

Since we receive a lot of issues around the topic of status code, I think we should improve message of it. So I've made it more descriptinve and actionable.

Improve exception message for DioException.badResponse

---

dio/lib/src/dio_exception.dart

We mainly construct the exception with a complete sentence, which will produce a double `.` in the message.
@ueman

💬 Remove dot from `DioException.connectionError(reason)`

---

dio/CHANGELOG.md
dio/lib/src/adapters/browser_adapter.dart
dio/lib/src/adapters/io_adapter.dart
dio/lib/src/options.dart
dio/test/timeout_test.dart
plugins/http2_adapter/CHANGELOG.md
plugins/http2_adapter/lib/src/connection_manager_imp.dart
plugins/http2_adapter/lib/src/http2_adapter.dart

Resolves #2022.
I've found that the `IOHttpClientAdapter` uses `Stopwatch` to integrate with `receiveTimeout`, which might cause infinity awaits if the stream has no response forever. This might be the root cause of #1739.
https://github.com/cfug/dio/blob/78f3813a8d8948887198ef628e5a2e2039489b03/dio/lib/src/adapters/io_adapter.dart#L194-L200

⚡ Ignore zero duration timeout

---

.github/workflows/tests.yml

Fix random failures during tests. Suggested by https://github.com/actions/runner-images/issues/6039#issuecomment-1209531257.

💚 Run `update` before `install` for `apt-get`

---

dio/CHANGELOG.md
dio/lib/src/transformers/sync_transformer.dart

No issues were fixed by this.
No semantic changes during the request.

⚡️ Remove the redundant stream transform

---

plugins/native_dio_adapter/CHANGELOG.md
plugins/native_dio_adapter/README.md
plugins/native_dio_adapter/example/lib/main.dart
plugins/native_dio_adapter/lib/src/native_adapter.dart

...to deprecate `cronetEngine` and `cupertinoConfiguration` for the `NativeAdapter`, to avoid platform exceptions.
Fixes #2039.

[native_dio_adapter] ✨ Adds `createCronetEngine` and `createCupertinoConfiguration`

---

plugins/http2_adapter/CHANGELOG.md
plugins/http2_adapter/lib/src/connection_manager_imp.dart
plugins/http2_adapter/test/http2_test.dart

[http2_adapter] ✨ Support non-TLS connection requests

---

dio/CHANGELOG.md
dio/lib/src/adapter.dart
dio/lib/src/adapters/browser_adapter.dart
plugins/native_dio_adapter/CHANGELOG.md
plugins/native_dio_adapter/lib/src/conversion_layer_adapter.dart

Prevent `Uint8List.fromList` if it already is `Uint8List`.

⚡️ Check `Uint8List` before doing byte conversions

---

dio/CHANGELOG.md
dio/lib/fix_data/fix.yaml
plugins/native_dio_adapter/CHANGELOG.md
plugins/native_dio_adapter/lib/fix_data/fix.yaml

https://github.com/flutter/flutter/wiki/Data-driven-Fixes
There are some limitations with `dart fix` data, such as we cannot modify a method parameter's arguments in a constructor (`onHttpClientCreate: (client)` to `createHttpClient: ()`, `stream` to `() => stream`).

🚨 Add `dart fix` configurations

---

dio/CHANGELOG.md
dio/lib/src/adapters/io_adapter.dart
dio/test/options_test.dart
dio/test/timeout_test.dart
plugins/http2_adapter/lib/src/http2_adapter.dart
plugins/http2_adapter/test/timeout_test.dart

Due to httpbun issues, I found a fake test with timeouts which tested with inappropriate queries (wrote `duration:` instead of `duration`), and also found an incorrect implementation of the response stream.
- Once `EventSink` is called with `add` or `addError`, it cannot be used again to make these calls, but it won't throw exceptions.
- `HttpClient` seems reused even if you created a new one.

🐛 Fix `receiveTimeout` for streamed responses

---

dio/lib/src/dio_mixin.dart
dio/test/dio_mixin_test.dart

`DioMixin` was never a real mixin before. Marking it to use `mixin class` once we use `>=3.0.0` as the SDK constraint.
The following exception will be raised if we roll the lower bound of the package to ^3.0.0:
`The class 'DioMixin' can't be used as a mixin because it's neither a mixin class nor a mixin.`

⚡️ Mark `DioMixin`'s todo and add tests

---

dio_workspace.iml
melos.yaml

Fix melos picking up example folders in random ignored folders

---

dio/CHANGELOG.md
dio/lib/src/adapter.dart
dio/lib/src/adapters/io_adapter.dart
dio/lib/src/dio/dio_for_native.dart
dio/lib/src/dio_mixin.dart
dio/lib/src/response/response_stream_handler.dart
dio/lib/src/transformers/sync_transformer.dart
dio/test/cancel_token_test.dart
dio/test/download_test.dart
dio/test/request_integration_test.dart
dio/test/response/response_stream_test.dart
dio/test/utils.dart
example/lib/extend_dio.dart
example/pubspec.yaml
plugins/http2_adapter/CHANGELOG.md
plugins/http2_adapter/lib/src/http2_adapter.dart
plugins/http2_adapter/pubspec.yaml
plugins/http2_adapter/test/request_test.dart
plugins/http2_adapter/test/utils.dart

* fixes #2025
This is a new approach that handles both IO & HTTP/2 adapters.
I also moved the `receiveTimeout` handling for IO & HTTP2 to the new helper.

Fix streamed response cancellation and progress

---

plugins/native_dio_adapter/CHANGELOG.md
plugins/native_dio_adapter/README.md
plugins/native_dio_adapter/pubspec.yaml

https://github.com/dart-lang/http/pull/1087

Bump cronet_http version to ^1.0.0

---

.github/workflows/tests.yml
dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/pubspec.yaml
example/lib/extend_dio.dart
example/pubspec.yaml
example_flutter_app/pubspec.yaml
plugins/cookie_manager/pubspec.yaml
plugins/http2_adapter/pubspec.yaml
plugins/native_dio_adapter/pubspec.yaml
pubspec.yaml

We decided for 2.19.0 half a year ago, so I think we can now safely go to Dart 3 for a 6.0.0 release.

Bump min Dart SDK to 3.0.0

---

dio/CHANGELOG.md
dio/lib/src/options.dart
dio/lib/src/utils.dart
dio/test/options_test.dart

⚡️ Support relative `baseUrl` on the Web platform

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart

I faced the same issue as #314 and #1869, and I also understand that it is not an error with the dio package but an error with the Flutter SDK / VScode, where VScode does not recognise the exceptions as handled when using Future.catchError(). 
Despite it not being a problem of this package, I believe "fixing" it such that it avoids the above mentioned problem is still the correct approach, the following modification avoids this problem, and allows the example Error Handling code on pub.dev works with VScode.

Escape from uncaught exceptions for IDEs

---

.github/workflows/tests.yml
plugins/http2_adapter/lib/src/http2_adapter.dart
plugins/http2_adapter/pubspec.yaml
plugins/http2_adapter/test/http2_test.dart
plugins/http2_adapter/test/pinning_test.dart
plugins/http2_adapter/test/redirect_test.dart
plugins/http2_adapter/test/request_test.dart
plugins/http2_adapter/test/timeout_test.dart

Fixes a redirect bug discovered during https://github.com/cfug/dio/pull/2077 where the adapter would fail to properly redirect if the location header contains a relative URL.

[http2] Fix Http2Adapter not redirecting for relative URLs

---

dio/lib/src/options.dart
dio/test/options_test.dart

Provide a readable error when the `baseUrl` is not matching the condition.

🥅 Throw argument error with invalid `baseUrl`

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/lib/src/interceptor.dart
dio/test/interceptor_test.dart

fix: Catch sync/async* exceptions in interceptor's handlers

---

dio/CHANGELOG.md
dio/lib/src/interceptor.dart
dio/test/interceptor_test.dart

🥅 Throws precise `StateError` for handler's duplicated calls

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/lib/src/interceptor.dart

Reverts #2139
Fixes #2167
Reopen #2138
Added tests were fake, so they remained effective after the revert.

Revert "Catch sync/async exceptions in interceptors' handlers"

---

dio/CHANGELOG.md
dio/lib/src/adapters/io_adapter.dart
dio_test/lib/src/test/cancellation_tests.dart
dio_test/lib/src/test/download_tests.dart
plugins/http2_adapter/CHANGELOG.md
plugins/http2_adapter/lib/src/http2_adapter.dart

🔥 Do not detaches sockets / terminates client stream

---

.github/workflows/tests.yml
dio/CHANGELOG.md
dio/lib/src/form_data.dart
melos.yaml

🚑️ Fix type promotions for the UTF-8 encoder

---

dio/CHANGELOG.md
dio/lib/src/adapters/io_adapter.dart
dio/lib/src/dio_exception.dart
dio/lib/src/interceptors/log.dart
plugins/http2_adapter/lib/src/connection_manager_imp.dart

- Improve some document comments.
- Change the parameter position of `DioException`'s constructors to make it most readable.
- Add constructor for `DioExceptionType.badCertificate`. There is also one reference in the plugin `http2_adapter`. But I don't know if changing that with an upgraded version is necessary.
https://github.com/cfug/dio/blob/1c2843a2fab1c3795272df1e81502616761e192e/plugins/http2_adapter/lib/src/connection_manager_imp.dart#L110-L115

Add constructor for DioExceptionType.badCertificate

---

.github/workflows/coverage_comment.yml
.github/workflows/tests.yml

When the coverage_comment workflow is triggered from a PR that originates from a fork, then the workflow event does not contain the PR number. But we need the PR number to attach the sticky coverage comment. So workaround this by storing the PR number in the workflow artifact that also contains the coverage result.

Fix coverage comment from forks

---

.github/dependabot.yaml

This should keep our workflows up-to-date.
@AlexV525 You removed the last dependabot configuration while migrating from diox. But I think it would be good to have this on.

Enable dependabot for github actions

---

.github/workflows/coverage_base.yml
.github/workflows/tests.yml

This should fix the baseline coverage generation. It now performs the exact same tests that the normal flow does.
It seems melos tasks can fail silently, in this case when the package filter is empty.

Fix coverage baseline generation

---

.github/workflows/coverage_base.yml
.github/workflows/tests.yml

The new version now supports listing individual changed files, not just packages and adds a flag that hides all files without changes to the coverage. We use that for the PR comment.
With https://github.com/VannaDii/pub-dev/pull/9 the `cobertura` package now also reports the correct line coverage.

Update coverage report action

---

plugins/web_adapter/lib/src/js_interop/adapter.dart

refactory `xhr.ontimeout` & optimize the code

---

.github/workflows/coverage_base.yml
melos.yaml

Trying to fix the wrong coverage for http2 plugin.

Actually run all test in the baseline 🙈

---

dio/CHANGELOG.md
dio/lib/src/form_data.dart
dio/lib/src/multipart_file.dart
dio/lib/src/utils.dart
dio/test/formdata_test.dart
dio/test/mock/_formdata
dio_test/lib/src/test/download_tests.dart

🐛 Applies strict type conversion for finalizing the multipart file

---

dio/CHANGELOG.md
dio/lib/src/interceptor.dart
dio/test/interceptor_test.dart

💬 Overrides `InterceptorState.toString()`

---

dio/lib/src/transformers/fused_transformer.dart
dio/lib/src/transformers/sync_transformer.dart
dio/lib/src/transformers/util/consolidate_bytes.dart
dio/test/transformer_test.dart

Follow up to #2239:
The more efficient Stream<UintList> -> Uint8List conversion can be backported to `SyncTransformer` & the extending `BackgroundTransformer`

backport improved byte consolidation to SyncTransformer and BackgroundTranformer

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/test/cancel_token_test.dart

🥅 Throw if cancelled before established

---

dio/CHANGELOG.md
dio/lib/src/dio_mixin.dart
dio/lib/src/transformers/fused_transformer.dart
dio/test/transformer_test.dart

Also fix three oversights in the transformer
- Fix parsing content as JSON when Content-Type is like `application/json` but `ResponseType == .plain`
- HEAD requests have an empty body, even when Content-Length is >0. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD . I did not take this into account. This is also fixed now.
- Respect custom decoders returning null

Set FusedTransformer as default

---

dio/CHANGELOG.md
dio/lib/src/interceptors/imply_content_type.dart
dio/lib/src/options.dart
dio/lib/src/transformer.dart
dio/lib/src/utils.dart
plugins/web_adapter/lib/src/html/adapter.dart

🧑‍💻 Move logs out from the adapter

---

dio/CHANGELOG.md
dio/lib/src/adapter.dart
dio/lib/src/compute/compute.dart
dio/lib/src/dio.dart
dio/lib/src/dio_mixin.dart
dio/lib/src/multipart_file.dart

From what understand, we added conditional `js_interop` imports that force `dart:html` imports into WASM builds.
Since we don't yet support WASM, I don't completely understand how it actually compiled to WASM before change.
For now we can just remove the conditional imports and add them back together with actual WASM support.
Hopefully fixes #2266

Attempt to fix WASM compile errors

---

dio/CHANGELOG.md
dio/lib/src/transformers/fused_transformer.dart
dio/lib/src/transformers/util/transform_empty_to_null.dart
dio/test/transformer_test.dart

fixes #2279 
This improves handling of the following case:
- ResponseType is json
- Server Content-Type is json
- Server Content-Length is nonzero
- Response Body is empty
This can happen in some cases according to HTTP spec (e.g. HEAD requests), but some servers return responses like this (see #2279) also in other cases, even if it violates the HTTP spec.
With #2250, in some of these cases dio would throw an exception, which caused a regression for some users; see #2279
I do believe that dio should handle these cases for gracefully,
This PR brings back the previous behavior of returning null.

fix: improve fallback to null on empty responses

---

dio/CHANGELOG.md
dio/lib/src/options.dart
plugins/web_adapter/lib/src/adapter.dart

Fixes https://github.com/cfug/dio/discussions/2306
The warning will be raised within the adapter.

🔥 Remove redundant warnings

---

dio_test/lib/src/test/basic_tests.dart

NeverSSL no longer supports H2 headers upgrade without TLS. All alternatives I've searched are not supported:
- http://www.gstatic.com/generate_204
- http://http.badssl.com/
- http://flutter.dev/
Surprisingly, http://flutter-io.cn/ supports all functionality. 😮

♻️ Use `flutter-io.cn` rather than `neverssl.com`

---

plugins/native_dio_adapter/CHANGELOG.md
plugins/native_dio_adapter/pubspec.yaml

supports cupertino_http ^2.0.0, which has to break changes that don't affect this package. 
No code changes. 
Also fix typo (`<=` -> `<` )  in pubspec.yaml which would support cronet_http 2.0.0, which is not released yet and might contain breaking changes which are not compatible with this package

chore(native_dio_adapter): support cupertino_http 2.0.0

---

scripts/melos_packages.dart

https://pub.dev/packages/melos/versions/6.3.0/changelog
```console
scripts/melos_packages.dart:47:23: Error: The getter 'pubSpec' isn't defined for the class 'Package'.
- 'Package' is from 'package:melos/src/package.dart' ('../../../.pub-cache/hosted/pub.dev/melos-6.3.1/lib/src/package.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'pubSpec'.
.where((e) => e.pubSpec.environment!.sdkConstraint!.allows(current));
^^^^^^^
```

💚 Fix melos package script

---

melos.yaml
scripts/melos_packages.dart

Picked and updated from https://github.com/cfug/dio/pull/2362

👷 Check bootstrappable package as a prehook of melos and log checked packages

---

dio/lib/src/interceptor.dart

The previous documentation for `QueuedInterceptor` could lead to misunderstandings about how concurrent requests are handled. The explanation suggested that requests would have to wait for the previous request to complete before being initiated.
This update clarifies that requests are processed in three independent queues: `onRequest`, `onResponse`, and `onError`. These queues run in parallel.

Fix: Clarify the behavior of concurrent requests in QueuedInterceptor

---

plugins/http2_adapter/CHANGELOG.md
plugins/http2_adapter/doc/migration_guide.md
plugins/http2_adapter/lib/src/connection_manager.dart
plugins/http2_adapter/lib/src/connection_manager_imp.dart
plugins/http2_adapter/lib/src/http2_adapter.dart
plugins/http2_adapter/test/http2_test.dart
plugins/http2_adapter/test/redirect_test.dart

The connection manager now established the transport with the given redirection record rather than reusing the previous transport.

🐛 Make cached connections respect redirections

---

dio/CHANGELOG.md
dio/lib/src/parameter.dart
dio/pubspec.yaml
dio/test/parameter_test.dart

Resolves https://github.com/cfug/dio/issues/2364
This PR addresses an issue with ListParam equality, where identical requests were not recognized as the same due to reference comparison of lists. This caused multiple identical requests to be sent to the server, even when caching was implemented.
Updated ListParam's operator == to use DeepCollectionEquality for proper deep equality comparison of list contents.
Added relevant unit tests to validate the fix and ensure no regression.
<br/>

Fix: Resolve ListParam equality issue for caching identical requests

---

plugins/web_adapter/lib/src/dio_impl.dart

🚚 Rename the parameter of `DioForBrowser`

---

dio/README-ZH.md
dio/README.md

Because none of the examples below explicitly declare a type, I believe the intended type is actually the Response response; at the top. However, it is not returning a Response; it is an array type.
It is an array type. When I copy and run it, it actually throws an error.
Although it’s not a big issue, I believe explicitly declaring the type would be better.
https://github.com/cfug/dio/blob/d6888cc4b1b085e6cf94c930ff9cb858c271d144/dio/README.md?plain=1#L115

docs: fix the return value type.

---

dio/CHANGELOG.md
dio/lib/src/cancel_token.dart
dio/test/cancel_token_test.dart

Calls `CancelToken.cancel` multiple times will update the internal error field to the last defined.

🐛 Do not allow update the error field after a cancel token has cancelled

---

plugins/native_dio_adapter/CHANGELOG.md
plugins/native_dio_adapter/lib/src/cronet_adapter.dart

Now the `CronetEngine` shall be closed along with the adapter and the client. This reduces the possibility with https://github.com/cfug/dio/issues/2300, learned from https://github.com/dart-lang/http/issues/1136#issuecomment-1960054016.
This PR cannot be effectively tested due to the unpublic closed state.
https://github.com/dart-lang/http/pull/1795

⚡ Close `CronetEngine` when closing the `CronetClient`

---

dio/CHANGELOG.md
dio/lib/src/multipart_file.dart
dio/lib/src/multipart_file/io_multipart_file.dart
dio/pubspec.yaml
dio/test/mock/_formdata
dio/test/multipart_file_test.dart

This should not be a breaking change unless the user implied the `application/octet-stream` before.

⚡️ Use `package:mime` to help determine the `content-type` of `MultipartFile` base on the provided `filename`
