cfug/dio

lib/src/Dio.dart
=> Revert "add some code lint in Future.then"

lib/src/dio.dart
Will provide feedback for upload progress indicators.  Modelled along the lines of the OnDownloadProgress in file Download.
Can probably look to add a similar approach to downloads.
Currently have 1 test failing, but don't believe this is due to these changes.  Appears an endpoint used for the test has moved (no returning a 302 rather than expected error).  Happy to resolve this test, but didn't want to jump around on it.
=> Adding an onUploadProgress Callback for Post Requests

README-ZH.md, README.md, example/dio.dart, lib/src/dio.dart, lib/src/dio_error.dart
You may wanna know which is the reqeust when you have CONNECT_TIMEOUT or RECEIVE_TIMEOUT.
=> Add request in DioError, fix format and typo

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Add  github templates
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios / android                          |      |
| Platform Version               | e.g.  1.5.0 / 12.0 / 9.0                              |      |
| Dio Version                    | e.g.  2.1.0 / 1.0.17                                  |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2 / Xcode 10.2.1              |      |
| Repro rate                     | e.g. all the time (100%) / sometimes x% / only once   |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            | …
=> Add github auto  generate issues && pull template

package_src/lib/src/form_data.dart, package_src/test/dio_test.dart
修复formdata的map 转换问题。同一key转换成 key[] 的格式。
...
=> fix formdata parse map error

example/options.dart, package_src/lib/src/dio.dart, package_src/test/dio_test.dart
=> feat: use baseUrl in RequestOptions as 1st priority

plugins/cookie_manager/README.md
Correct import path for dio_cookie_manager in the Usage section
=> Correct import path

dio/lib/src/options.dart
I'am new to flutter, but what does this `String ` mean in line 192: 
` contentType: String ?? this.contentType,`?
This lead to an error when `merge()` is called.
=> An incorrect variable in assignment?

dio/lib/src/form_data.dart, dio/lib/src/options.dart
=> 处理上传 oss 及 超时时间不生效问题

dio/lib/src/form_data.dart
This merge request fixes the following issues: #563, #566
This merge request reverts 213a476 from #562 because it breaks uploading files.
See issues linked above for details.
=> Fix broken feature: uploading files

dio/CHANGELOG.md
- [x ] I have read the [Documentation](https://pub.dartlang.org/packages/dio)
- [ x] I have searched for a similar pull request in the [project](https://github.com/flutterchina/dio/pulls) and found none
- [ x] I have updated the documentation (if necessary)
Fixed markdown.
...
=> Fixed markdown in changelog file

README.md
FormData wrong function was used in example.
from() instead of fromMap()
...
=> minor change in example (FormData)

README.md
I think the current version of the README is not clear. I changed the description.
However, I'm not a native English speaker, so if you think I misunderstood the issue or my changes aren't any better than the original, feel free to close the issue.
=> Update README: clarify breaking changes

dio/lib/src/transformer.dart
This merge request fixes / refers to the following issues:
Fixes #578
Instead of using a large `List<int>`, I keep references to the data chunks and at the very end create a `Uint8List` and fill it with the chunks. This seems to reduce memory allocation considerably.
=> fix(transformer): reduce memory consumption

README.md
This merge request fixes / refers to the following issues:
https://github.com/flutterchina/dio/issues/294
Update README with a reference to dio_firebase_performance package
=> Add note about dio_firebase_performance to README

README-ZH.md
=> FIX: FormData example error in README-ZH.md

plugins/http2_adapter/lib/src/http2_adapter.dart
See  plugins/http2_adapter/lib/src/http2_adapter.dart#L64-L69
https://github.com/flutterchina/dio/blob/21136168ab39a7536835c7a59ce0465bb05feed4/plugins/http2_adapter/lib/src/http2_adapter.dart#L64-L69
Closing outgoingMessages `stream.outgoingMessages.close();` will send a zero length DataStreamMessage to signal `endOfStream` however the `requestStream` was null.
Some h2 servers would reject zero length DataStreamMessage (response :status 501).
We need mark `endOfStream` to true in this case:
`transport.makeRequest(headers, endStream: true)`
=> Avoid sending zero length data stream message to h2 server

example/flutter_example/lib/main.dart, example/flutter_example/lib/routes/request.dart
=> Added elevated button

dio/lib/src/form_data.dart, dio/lib/src/options.dart, dio/lib/src/parameter.dart, dio/lib/src/transformer.dart, dio/lib/src/utils.dart, dio/test/encoding_test.dart
Support different list formats per parameter in query parameters and `x-www-url-encoded` body data.
=> Support different list formats per parameter

dio/lib/src/dio_mixin.dart
This merge request fixes / refers to the following issues: #1173 
Since the stack trace of errors was previously cut off, it was very hard to find the source of network-related bugs in large apps. (As described in #1173)
Therefore, this PR passes the full stack trace to `assureDioError` and, by extension, also to the `DioError` object.
=> Fixed incomplete stack trace

dio/lib/src/adapter.dart
Fix download performance on Web see https://github.com/dart-tools/dio_http/commit/2c243d99cc7c1a05c582d3a36b65f7b92346a580
...
Credits to @jgoyvaerts and @marukami
=> Fix download performance issue on Web

dio/lib/src/options.dart
There was one space character too much.
=> docs: remove unnecessary space

.gitignore, dio/test/download_test.dart
The download test creates a markdown file, this moves it inside the folder and adds it to gitignore.
=> Move and gitignore download test file

.github/workflows/dio.yml, .github/workflows/plugin_cookie_manager.yml, .github/workflows/plugin_http2_adapter.yml, .github/workflows/test-report.yml, plugins/cookie_manager/analysis_options.yaml, plugins/cookie_manager/dart_test.yaml, plugins/cookie_manager/pubspec.yaml, plugins/cookie_manager/test/basic_test.dart, plugins/http2_adapter/analysis_options.yaml, plugins/http2_adapter/dart_test.yaml, plugins/http2_adapter/lib/src/connection_manager_imp.dart, plugins/http2_adapter/lib/src/http2_adapter.dart, plugins/http2_adapter/pubspec.yaml
=> Add CI workflows for plugins

README-ZH.md, README.md, dio/README-ZH.md, dio/README.md
The current readme doesn't display correctly on pub.dev, this PR fixes that.
=> Fix section about request method aliases in readme

.github/workflows/dio.yml, .github/workflows/example-app.yml, .github/workflows/example.yml, .github/workflows/plugin_cookie_manager.yml, .github/workflows/plugin_http2_adapter.yml
=> [ci] Add wildcard develop branches to workflows

README-ZH.md, README.md, dio/README-ZH.md, dio/README.md, dio/lib/src/adapters/browser_adapter.dart, dio/lib/src/adapters/io_adapter.dart, dio/lib/src/entry/dio_for_native.dart, dio/lib/src/options.dart, dio/test/download_test.dart, dio/test/options_test.dart, dio/test/readtimeout_test.dart, dio/test/request_test.dart, example/lib/dio.dart, example/lib/download.dart, example/lib/http2_adapter.dart, example/lib/options.dart, example/lib/post_stream_and_bytes.dart, example/lib/request_interceptors.dart, example_flutter_app/lib/routes/request.dart, plugins/http2_adapter/example/example.dart, plugins/http2_adapter/lib/src/connection_manager.dart, plugins/http2_adapter/lib/src/connection_manager_imp.dart, plugins/http2_adapter/test/http2_test.dart
Fixes #1375
This is a breaking change
=> Various timeout parameter replaced with durations instead of ints

dio/lib/browser_imp.dart, dio/lib/io.dart, dio/lib/native_imp.dart, dio/lib/web.dart, dio/test/echo_adapter.dart, dio/test/mock_adapter.dart, example/lib/extend_dio.dart, example/lib/formdata.dart, example/lib/proxy.dart
Closes #1362 (partially)
This introduces a single import for ´dio/io.dart´ and ´dio/web.dart´
=> Feature: Improve exports

.github/workflows/dio.yml, .github/workflows/plugin_cookie_manager.yml, .github/workflows/plugin_http2_adapter.yml
=> ci: Remove dev channel, now always points to beta

README.md
This PR fixes the table of contents by updating both `Transformer` and `Using proxy`'s URLs.
...
=> docs: fix table of contents links

.github/workflows/dio.yml, .github/workflows/plugin_cookie_manager.yml, .github/workflows/plugin_http2_adapter.yml, .github/workflows/test-report.yml, dio/test/upload_stream_test.dart
=> ci: Upload and collect test results for all sdks

.github/workflows/test-report.yml
=> ci: Run checkout in test reporter workflow

README.md, dio/README.md
=> 📃 Fix link issue and mistake in docs.

dio/CHANGELOG.md
Add the missing content and move published content in the CHANGELOG.
=> 🚑 Correct CHANGELOG

plugins/cookie_manager/CHANGELOG.md, plugins/cookie_manager/lib/src/cookie_mgr.dart, plugins/cookie_manager/pubspec.yaml, plugins/cookie_manager/test/cookies_test.dart
=> 🐛 fix cookies override problems

.github/workflows/check_issues_access.yml
=> 👷 Not allow users without write access to create "infra" or blank issues

README-ZH.md, README.md, dio/README-ZH.md, dio/README.md
- Minor fix to the footer section of the project README files.
=> 📄 update/fix footer section of the docs

.github/PULL_REQUEST_TEMPLATE.md
The comment would be an example. Related to #1662. This would be a temporary solution until we can have a robust check.
=> Add the `CHANGELOG` requirement in the PR template

dio/README-ZH.md, dio/README.md
=> chore: add flutter_ume_kit_dio

.github/workflows/publish.yml
Related to #1633
Credit and huge thanks to @CaiJingLong !
See https://github.com/CaiJingLong/dio/issues/1 and https://github.com/CaiJingLong/dio/releases for previous test records.
=> 👷 Use automatic publish tool

dio/test/interceptor_test.dart
The tests for `ImplyContentTypeInterceptor` were sorely lacking, so I've added a few basic expectations to test its behavior.
=> Add functionality tests for `ImplyContentTypeInterceptor`

dio/test/options_test.dart
Adds a corresponding test for issues like #1693.
No need to update `CHANGELOG.md` since it only affects tests without package code base changes.
=> ✅ Add headers test for redirects

dio/CHANGELOG.md, dio/lib/src/dio_mixin.dart, dio/test/mock/adapters.dart, dio/test/options_test.dart
=> 🔥 Remove force convert for the response body

dio/lib/src/interceptor.dart
=> Document that interceptors aren't triggered by redirects

dio/lib/src/dio.dart, dio/lib/src/options.dart, dio/lib/src/response.dart, dio/lib/src/transformer.dart
Small update on the docs making reference to `onProgress` instead of `onReceiveProgress`
=> fix: update onReceiveProgress references in docs

dio/CHANGELOG.md, dio/lib/src/interceptors/imply_content_type.dart, dio/test/interceptor_test.dart
=> 🚀 Imply `List<Map>` as JSON content

dio/CHANGELOG.md, dio/lib/src/utils.dart, dio/test/formdata_test.dart
=> 🚑 Fix FormData encoding (#1741)

plugins/native_dio_adapter/lib/src/cronet_adapter.dart, plugins/native_dio_adapter/pubspec.yaml, plugins/native_dio_adapter/test/conversion_layer_adapter_test.dart
https://github.com/dart-lang/test/issues/1977
=> [native_dio_adapter] Fix CI

dio/CHANGELOG.md, dio/lib/src/utils.dart, dio/test/basic_test.dart, dio/test/browser_test.dart, dio/test/exception_test.dart, dio/test/formdata_test.dart, dio/test/utils.dart
In relation to #1741 
Fixes #1741 
Fixes #1758
=> [dio] Fix FormData encoding regression for maps with dynamic keys

.github/workflows/tests.yml, plugins/http2_adapter/CHANGELOG.md, plugins/http2_adapter/README.md, plugins/http2_adapter/example/example.dart, plugins/http2_adapter/lib/src/client_setting.dart, plugins/http2_adapter/lib/src/connection_manager_imp.dart, plugins/http2_adapter/test/http2_test.dart
This merge request fixes / refers to the following issues: #1259 #905
Added proxy tunnel to http2 adaptor
=> [http2_adapter] HTTP/2 proxy

plugins/cookie_manager/CHANGELOG.md, plugins/cookie_manager/lib/src/cookie_mgr.dart, plugins/cookie_manager/test/cookies_test.dart
=> [cookie_manager] 🐛 Fix redirection handling

plugins/cookie_manager/CHANGELOG.md, plugins/cookie_manager/pubspec.yaml
=> Bump cookie_jar from 3.x to 4.0.x

.github/workflows/tests.yml
Significantly reduces the overall actions running duration.
There are no action balance in our org at this moment so jobs are expected not to be ran.
=> Remove example builds

dio/CHANGELOG.md, dio/lib/src/form_data.dart, dio/test/formdata_test.dart
Form data now accept null value
=> Form data allow null value

plugins/cookie_manager/lib/src/cookie_mgr.dart
=> Fix Unnecessary use of parentheses found with Dart 3

dio/README-ZH.md, dio/README.md
=> Missing README update for createHttpClient

.github/workflows/publishable.yml, .github/workflows/tests.yml
I created a new 6.0.0 branch where we can start getting rid of all the deprecated code etc.
This PR just enables  workflows to run against this branch.
=> Run workflows on 6.0.0 branch

dio/CHANGELOG.md, dio/lib/io.dart, dio/lib/src/adapters/io_adapter.dart, dio/migration_guide.md
=> Remove deprecated `DefaultHttpClientAdapter`

dio/CHANGELOG.md, dio/lib/src/dio_exception.dart, dio/migration_guide.md
=> Remove deprecated `DioError` and `DioErrorType`

dio/lib/src/adapters/io_adapter.dart
=> Fix Dart 3.0.1 formatting

dio/CHANGELOG.md, dio/README-ZH.md, dio/README.md, dio/lib/src/transformer.dart, dio/lib/src/transformers/sync_transformer.dart, dio/migration_guide.md
=> Remove deprecated `DefaultTransformer`

README-ZH.md, README.md, dio/CHANGELOG.md, dio/README-ZH.md, dio/README.md
Resolves #1843.
Apparently, the previous tips are not obvious enough.
=> Add breaking changes tip in docs

dio/CHANGELOG.md, dio/migration_guide.md
Quick follow-up for https://github.com/cfug/dio/pull/1827
=> Fix min Dart SDK in 6.0.0 changelog

.github/workflows/tests.yml, plugins/native_dio_adapter/CHANGELOG.md, plugins/native_dio_adapter/README.md, plugins/native_dio_adapter/pubspec.yaml
Fixes https://github.com/cfug/dio/issues/1845
=> Update native dio adapter

.github/workflows/publish.yml
Migrate the release action from `v1` to `v2`.
=> Use v2 release action

dio/CHANGELOG.md, dio/lib/src/dio_mixin.dart, dio/test/mock/http_mock.dart, dio/test/mock/http_mock.mocks.dart, dio/test/upload_test.dart
* add test to ensure that binary data is never transformed
* fixes #1832
=> Improve performance of byte data on IO platform

dio/README.md
=> Fix createHttpClient example in README

dio/CHANGELOG.md, dio/lib/src/dio_exception.dart
The deprecation message was providing a wrong hint.
=> Fix deprecation warning

dio/CHANGELOG.md
Just another fix for the release action to work.
=> Fix changelog for 5.2.1

dio/CHANGELOG.md, dio/pubspec.yaml
=> Remove `http` from `dev_dependencies`

dio/CHANGELOG.md, dio/lib/src/dio/dio_for_native.dart, dio/test/download_test.dart
=> Fix for Dio.download not cleaning the file on data handling error

plugins/cookie_manager/CHANGELOG.md, plugins/http2_adapter/CHANGELOG.md, plugins/native_dio_adapter/CHANGELOG.md
=> Update CHANGELOG for packages

dio/test/stacktrace_test.dart
- Change `SocketException on request` to be platform-independent.
- Improve the readability of `SocketException on response`.
=> Improve tests

dio/CHANGELOG.md, dio/test/options_test.dart, dio/test/request_test.dart, plugins/native_dio_adapter/README.md
- Fix typos.
- Replace the less common "asynchronized" with the more common "asynchronous" to make the analyzer happy.
- Replace non-breaking spaces (NBSP) with a regular space.
=> Fix typos and improve the document

plugins/http2_adapter/CHANGELOG.md, plugins/http2_adapter/lib/src/http2_adapter.dart, plugins/http2_adapter/test/http2_test.dart
=> [http2_adapter] Fix redirect not working

.github/ISSUE_TEMPLATE/bug.yml
I always have to asks this, so I think this makes sense.
=> Extend the bug template with OS multiselect

dio/lib/src/dio_exception.dart
Further improve exception messages.
=> Improve exception messages

plugins/native_dio_adapter/CHANGELOG.md, plugins/native_dio_adapter/pubspec.yaml
=> feat(native_dio_adapter): bump cronet_http dependency

.github/workflows/tests.yml, dio/lib/src/compute/compute.dart, dio/lib/src/compute/compute_io.dart, dio/lib/src/compute/compute_web.dart, plugins/native_dio_adapter/CHANGELOG.md, plugins/native_dio_adapter/example/pubspec.yaml, plugins/native_dio_adapter/pubspec.yaml
Fix lint issues from https://github.com/cfug/dio/actions/runs/6599112276/job/17927803638?pr=2005
=> Fix lint issues

dio/README-ZH.md, dio/README.md
Fixes https://github.com/cfug/dio/issues/2012
Replaced **IOClientAdapter** to **IOHttpClientAdapter** on both readme and replaced **BrowserClientAdapter** to **BrowserHttpClientAdapter** on both readme.
=> Changes made in both Readme files

.github/workflows/tests.yml, scripts/dart_test.sh
Helps to determine exceptions occurrences during Dart tests.
=> 👷 Divide Dart packages tests by platforms

README-ZH.md, README.md, dio/README-ZH.md, dio/README.md
Helps the dio topic to gather packages, and packages to get more relevance.
=> 📝 Add topic suggestion

dio/.gitignore, dio/dart_test.yaml, dio/test/download_test.dart, dio/test/exception_test.dart, dio/test/pinning_test.dart, plugins/cookie_manager/dart_test.yaml, plugins/cookie_manager/test/basic_test.dart, plugins/http2_adapter/dart_test.yaml, plugins/http2_adapter/test/http2_test.dart, plugins/http2_adapter/test/pinning_test.dart, scripts/dart_test.sh
* skip tests requiring specific setup (proxy, certificates) by default, use `-P all` in CI to run all tests
* automatically cleanup temp/downloaded files in tests
* remove some logging from tests
=> Skip tests requiring specific setup by default

dio/lib/src/dio_mixin.dart
=> Remove legacy null check

dio/CHANGELOG.md, dio/lib/src/response/response_stream_handler.dart, dio/test/response/response_stream_test.dart
=> 🐛 Stop watching the receive timeout after cancelled

dio_test/lib/src/test/download_stream_tests.dart
The GitHub runner is much faster than our configurations, apparently.
=> ✅ Fix download stream tests

.github/workflows/tests.yml
This should allow us to use actions in that create comments etc.
The workflows are being run on. the code from the main branch.
=> Run test workflow on pull_request_target event

.github/workflows/tests.yml
=> Add test coverage PR comment action

dio/lib/src/form_data.dart
Fixes exception caused by #1201
=> 🚑️ Fix `FormData.readAsBytes`

dio_test/lib/src/test/basic_tests.dart
=> ✅ Fix non-TLS requests test

plugins/web_adapter/lib/src/js_interop/adapter.dart
=> refactory `xhr.upload.onprogress`

dio/README-ZH.md, dio/README.md, dio/lib/src/options.dart
=> 💡 Improve docs and comments about options merging

dio/CHANGELOG.md, dio/lib/src/transformer.dart, dio/test/transformer_test.dart
=> 🥅 Catch `MediaType` parse exception in `Transformer.isJsonMimeType`

plugins/web_adapter/CHANGELOG.md
=> 🧑‍💻 Move logs out from the adapter, pt.2

CODEOWNERS
https://github.com/orgs/cfug/teams/dio-core
=> Switch `CODEOWNERS` from `devs` to `dio-core`

dio/README.md
=> Fixes cfug/dio#2298

dio/README-ZH.md, dio/README.md
You can jump to the example directly from your browser.
=> Add README examples document jump

dio/README.md
=> docs: Update custom cache interceptor link in README.md

dio/example/dio.dart
The link is broken. However, the one I modified may not be the best, but at least it is correct.
=> docs: modify it to the correct example link.
